use join-with that works in GNU Make 4.3
no substitution was occurring for the HPP_FILES list, causing the
merge-headers to panic and fail because the command arguments were not
split properly when executing the command from DependencyGraph.new

```
thread 'main' panicked at 'clang++-11 ["-MT", "alloc.hpp api.hpp bytes.hpp comment.hpp decoded_input.hpp decoder.hpp diagnostic.hpp loc.hpp magic_comment.hpp messages.hpp nodes.hpp parser_options.hpp parser_result.hpp shared_byte_list.hpp source_line.hpp string.hpp token_rewriter.hpp token.hpp token_ids.hpp", "-MM", "alloc.hpp api.hpp bytes.hpp comment.hpp decoded_input.hpp decoder.hpp diagnostic.hpp loc.hpp magic_comment.hpp messages.hpp nodes.hpp parser_options.hpp parser_result.hpp shared_byte_list.hpp source_line.hpp string.hpp token_rewriter.hpp token.hpp token_ids.hpp"] returns incompatible output:
', src/dependency_graph.rs:28:9
```